### ISSUE TITLE
Turtlestitch .dst file causes Brother SE600 to restart

### ISSUE THREAD

**Issue by ohmygodwin** [backface/turtlestitch#117]
For some of my students, when they select their .dst file on the Brother SE600, the machine shuts down and restarts. I have tried using different USB drives and even had them email me their files for me to transfer, but it keeps happening. It is happening to ~15% of my students, but not the rest of us!

**Comment by backface** [comment]
sorry for the late reply. That's an interesting one. 
We'd need to track down what's different with thos 15% compared to the others. 
Can you share such a file with us?

**Comment by backface** [comment]
closing due to inactiviy
