### ISSUE TITLE
'Change brightness by' in Colors fails with 'TypeError this.changebrightnes is not a function'

### ISSUE THREAD

**Issue by rmillwood** [backface/turtlestitch#125]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/2338141/198988961-d04bb031-5e61-4e27-948b-1f74a5301e34.png">

**Comment by backface** [comment]
thx richard! nice typo. should be fixed if you reload (potentially also from cache?)

**Comment by rmillwood** [comment]
Is fixed in current version, also needed in beta :)

I use colour change to help me debug code - I can see which bits of my pattern belong to which bits of my code, so han=dy to have this fixed, although otherwise fairly irrelevant!

Thanks!

**Comment by backface** [comment]
now also in beta. good to hear someone is in fact using/testing it!
