### ISSUE TITLE
Point towards block

### ISSUE THREAD

**Issue by backface** [backface/turtlestitch#28]
Point towards block: mouse pointer is the only choice, so why a drop
down menu?

**Comment by xota** [comment]
Left over form Snap! and Scratch where you have the option to choose other sprites. With only one sprite it makes little sense in TurtleStitch (well it makes people feel home).

Bromagosa asks in different issue for "point towards x: … y: …" which maybe related. Albeit I don't think blocks should differ to much form their Snap/Scratch ancestors.

**Comment by backface** [comment]
Re-investigation the issue, I find we have three options here in hat current version (that is in testing, not yet the stable live version on the turtleStitch's site): mouse-pointer, center, random position. 

As the only other reasonable option would be to remove this block, I opt for leaving it as it is and closing this issue.

In addition, I just added the new block as in the  "point towards x: … y: …" feature request by Bromagosa.
