### ISSUE TITLE
unscheduled lines

### ISSUE THREAD

**Issue by nathalierun** [backface/turtlestitch#67]
Here is my recursive Sierpinski triangle.
https://www.turtlestitch.org/users/nathalierun/projects/Sierpinski
![image png 480 x 360 pixels](https://user-images.githubusercontent.com/17542520/50447772-e6687480-0936-11e9-8c44-e8268873a92f.png)

I do not understand these unscheduled lines... If someone could help...
Notice that I don't have the problem when I open it with Snap!

**Comment by backface** [comment]
Sorry for the late answer (but Andrea sent you a personal email to my knowledge).
I don't see a bug in the software here, you need to take care to put the pen up (jump stitch for Turtlestitch) before doing these connections...
