### ISSUE TITLE
block variable not available to use!

### ISSUE THREAD

**Issue by rmillwood** [backface/turtlestitch#71]
![image](https://user-images.githubusercontent.com/2338141/60018395-1e046f00-9683-11e9-86df-7df7e1207b59.png)

The pop-up menu for piece "change <variable> by 1" wouldn't let me choose the block variable n

**Comment by rmillwood** [comment]
Nor would the "set <variable> to " allow it

**Comment by rmillwood** [comment]
Since working further, I think I found that my jigsaw pieces weren't joined up and this may be the cause of the variable not being available in the 'make your own block' editor.

**Comment by backface** [comment]
This is an explanation! Yes this may have caused the variables not being available. You can confirm it is working now?
