### ISSUE TITLE
Mouse over text Turtlestitch menu

### ISSUE THREAD

**Issue by xota** [backface/turtlestitch#80]
It looks like the items "Hide turtle" and "Ignore embroidery warnings" have the same mouseover text, namely "uncheck to show turtle"/"check to hide turtle"
![PastedGraphic-1](https://user-images.githubusercontent.com/5808570/64124740-19a5b200-cda8-11e9-9184-d7b0d84ed023.png)

**Comment by backface** [comment]
right. fixed
https://github.com/backface/turtlestitch/commit/2fc89ba34042724dc9ed12cc92d6ddbb37ef3e4d
