### ISSUE TITLE
Africa wants offline version, need for page with instructions

### ISSUE THREAD

**Issue by xota** [backface/turtlestitch#81]
One of the things I learned at Scratch2019NBO is that running Turtlestitch online sin't always possible in the African context.
Snap has a very comprehensive [page](https://snap.berkeley.edu/offline) explaining how to run offline, Turtlestitch should have the same.

**Comment by backface** [comment]
There is the original SNAP! offline documentation still in the repo and it certainly applies as such to TurtleStitch as well. But you are right. If this feature is useful or necessary for the audience it should be properly tested, documented and made available (linked) as an 'offline' release...

**Comment by backface** [comment]
https://github.com/backface/turtlestitch/blob/master/OFFLINE.md

**Comment by xota** [comment]
The point is that we can't assume knowledge about the Snap connection, nor about Github.

So we need a page turtlestich.org/offline that

1. explains that Turtlestitch works offline with limitations (or explain that that opening / saving is replaced by importing / exporting)
2. provides a link to a convenient download
3. gives instructions on what to do with the download

**Comment by backface** [comment]
https://github.com/backface/turtlestitch/commit/c7e77e9172bec6a933580c2dc8cdff09f65c7950

https://www.turtlestitch.org/page/offlineuse
