### ISSUE TITLE
Size of the document .dst

### ISSUE THREAD

**Issue by UrticaDesign** [backface/turtlestitch#82]
Hi,
I am a new user of TurtleStitch (Thanks!).
I am more a user than one who can help with the coding in this TurtleStitch project...
I discovered that when I exported a .dst file to the embroidery sewing machine it would not «discover» the file. Then I opened the .dst file in InkStitch, changed the document size of this .dst file (as small as I could around the design in the file + 1 mm on each side). And I saved it as a new .dst file. This file could the embroidery sewing machine «see» and the sewing of the design was running fine.
I hope this can help...

Regards Hanne

**Comment by backface** [comment]
That's interesting. Which machine do you have? Could you upload/attach both files here?
