### ISSUE TITLE
Feature Request: loading bitmap images

### ISSUE THREAD

**Issue by backface** [backface/turtlestitch#85]
Create a block to load bitmap images

**Comment by thetha** [comment]
This will be not possible in my opinion. Have a look at Wilcom Hatch. They have this features for a price of 1000€.

**Comment by backface** [comment]
two possible usage scenarios: 
1. load as a background image on stage, so it can be traced
2. load it as array/list for further processing

**Comment by backface** [comment]
https://github.com/backface/turtlestitch/commit/b050fd22e874c9855e69772d9c5205fb6fc67e40
