### ISSUE TITLE
bottom area of the stage disabled when toggle the stage to  full screen mood in beta version! 

### ISSUE THREAD

**Issue by Simon-Mong** [backface/turtlestitch#93]
About 1/3 area of the bottom area turns to grey and  disabled when I toggled the stage to full screen mood. I'll try it on other computers.

**Comment by backface** [comment]
ok. something with stage (re)sizing changed in Snap6. A first fix is added in https://github.com/backface/turtlestitch/commit/f1e3001d2b6927266b0516e9baa81dd24119f067 (branch snap6)

**Comment by Simon-Mong** [comment]
Yes,Snap!6 changed a lot in rendering. I think you are working on it. Now when the "toggle" icon is clicked the stage goes to the traditional app mode of Snap! but the "toggle" icon disappeared and it could not goes back. And there is another problem. When the stage stays in normal state the turtle goes to the mouse point when then block "goto mousepoint" is run. But when it is toggled to the app mode the turtle always goes to the wrong point when that block is run.

**Comment by Simon-Mong** [comment]
![图片](https://user-images.githubusercontent.com/30740101/125310419-23fe4300-e365-11eb-8054-7e64e31aafbe.png)
Some grey rectangles or shadows appears temporarily.

**Comment by backface** [comment]
ok. the app mode toggle button should be back. I don't currently know where the grey rectangles come from. 
'go to mousepointer' should also work again, at least mostly. It's currently off even in the stable version once you start zooming in or out in app mode (https://github.com/backface/turtlestitch/issues/94)

**Comment by backface** [comment]
> Some grey rectangles or shadows appears temporarily.

I added a hackish attempt to get rid of those scheduling an additional rerender after a few milliseconds. this seems to work
(but the main problem is that the updated Snap and Turtlestitch three.js renderer seem to try to write into the same context now.)

**Comment by Simon-Mong** [comment]
I add an isDirty method to actively detect if the stage is dirty and rerender the stage. It prevents the shadows from being generated when the scripts are dragged over the stage and some unknown reasons. But your hack method is still important because the reason of  how shadows of the only sprite come from the interactive events is still unclear and the hack method does work in these situations.

**Comment by backface** [comment]
so I'd say this is solved now?
