### ISSUE TITLE
mouse positon reporter are off when zooming in - or out - in appMode/Fullscreen

### ISSUE THREAD

**Issue by backface** [backface/turtlestitch#94]

**Comment by backface** [comment]
this applies to both the stable and beta versions!

**Comment by Simon-Mong** [comment]
Oh,I fixed it. It's really an interesting problem. I found it's just a question of how to keep the size of the grid unit proportional to the size of the stage.

**Comment by backface** [comment]
fixed with https://github.com/backface/turtlestitch/pull/96. thx Simon
